# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

first_addend = 0
second_addend = 1

sum_of_even = 0
while second_addend < 4000000:
    second_addend = first_addend + second_addend
    first_addend = second_addend - first_addend
    if second_addend % 2 == 0:
        sum_of_even += second_addend

print(sum_of_even)

